# Generated by Django 4.1.7 on 2023-03-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_casa', models.IntegerField(default=0)),
                ('td_fuera', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicion.competicion')),
                ('entrenador_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='competicion.entrenador')),
                ('entrenador_fuera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuera', to='competicion.entrenador')),
            ],
        ),
    ]
