# Generated by Django 4.1.7 on 2023-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicion', '0002_competicion_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='clasica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competicion',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
    ]
