# Generated by Django 4.1.7 on 2023-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicion', '0003_competicion_clasica_competicion_oculta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='tabla',
            field=models.JSONField(default=dict),
        ),
    ]
