# Generated by Django 4.1.7 on 2023-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicion', '0004_alter_competicion_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='tabla',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
